# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: YOLO Documentation
site_url: https://shreyaskamathkm.github.io/yolo/
repo_url: https://github.com/shreyaskamathkm/yolo
repo_name: shreyaskamathkm/yolo

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            members_order: source
            show_submodules: false

nav:
  - Home: index.md
  - Get Started:
    - Quick Start: 0_get_start/0_quick_start.md
    - Introduction: 0_get_start/1_introduction.md
    - Installation: 0_get_start/2_installations.md
  - Tutorials:
    - All In One: 1_tutorials/0_allIn1.md
    - Setup Config: 1_tutorials/1_setup.md
    - Build Model: 1_tutorials/2_buildmodel.md
    - Dataset: 1_tutorials/3_dataset.md
    - Train & Validate: 1_tutorials/4_train.md
    - Inference: 1_tutorials/5_inference.md
  - Model Zoo:
    - Object Detection: 2_model_zoo/0_object_detection.md
    - Segmentation: 2_model_zoo/1_segmentation.md
    - Classification: 2_model_zoo/2_classification.md
  - Custom YOLO:
    - Model: 3_custom/0_model.md
    - Data Augmentation: 3_custom/1_data_augment.md
    - Loss Function: 3_custom/2_loss.md
    - Custom Task: 3_custom/3_task.md
  - Deploy:
    - Deploy Model: 4_deploy/1_deploy.md
    - ONNX: 4_deploy/2_onnx.md
    - TensorRT: 4_deploy/3_tensorrt.md
  - Features:
    - Small Object: 5_features/0_small_object.md
    - Version Convert: 5_features/1_version_convert.md
    - IPython: 5_features/2_IPython.md
  - API Reference:
    - Solver & Optimizer: 6_function_docs/0_solver.md
    - Tools: 6_function_docs/1_tools.md
    - Module: 6_function_docs/2_module.md
    - Config: 6_function_docs/3_config.md
    - Dataloader: 6_function_docs/4_dataloader.md
  - Contributing: CONTRIBUTING.md
