trainer:
  accelerator: auto
  device: auto
  precision: 32-true  # use bf16-mixed on Ampere+ GPU, 16-mixed can produce NaN
  sync_batchnorm: True
  log_every_n_steps: 1
  gradient_clip_val: 10
  gradient_clip_algorithm: norm
  deterministic: True

image_size: [640, 640]

out_path: runs
exist_ok: True

seed: 10
use_wandb: False
use_tensorboard: False

task_type: detection

weight: True # Path to weight or True for auto, False for no pretrained weight

model:
  compile:
    enabled: True
    mode: default
    fullgraph: False
    dynamic: False
    backend: inductor
