defaults:
  - task: inference
  - model: v9-c
  - dataset: coco
  - general
  - _self_

hydra:
  run:
    dir: runs/${task.task}/${name}

name: inference_trt
weight: exports/v9-c.ep

task:
  backend: trt
