name: Validate and Infer

on:
  workflow_call:

jobs:
  validate_and_infer:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        python-version: ['3.11', '3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: make install

      - name: Cache model weights
        uses: actions/cache@v4
        with:
          path: weights
          key: ${{ runner.os }}-weights
          restore-keys: |
            ${{ runner.os }}-weights

      - name: Run Validation
        run: |
          python -m yolo task=validation use_wandb=False dataset=mock
          python -m yolo task=validation use_wandb=False dataset=mock model=v9-s
          python -m yolo task=validation use_wandb=False dataset=mock name=AnyNameYouWant

      - name: Run Inference
        run: |
          python -m yolo task=inference use_wandb=False
          python -m yolo task=inference use_wandb=False model=v7
          python -m yolo task=inference use_wandb=False +quiet=True
          python -m yolo task=inference use_wandb=False name=AnyNameYouWant
          python -m yolo task=inference use_wandb=False image_size=\[480,640]
          python -m yolo task=inference use_wandb=False task.nms.min_confidence=0.1
          python -m yolo task=inference use_wandb=False task.fast_inference=deploy
          python -m yolo task=inference use_wandb=False task.data.source=tests/data/images/val
